// GENERATED by tools/generate_adapters.py — do not edit.
//
// One definition of what the pipeline reads, shared by the uploader and the refresh.
// The Python registry at .claude/skills/refresh-tvsm-dashboard/scripts/sources.py is the
// source; this is a projection of it, checked in so the browser bundle needs no Python,
// and asserted equal by the test suite so it cannot go stale.
//
// Note what is NOT here: header rows, column windows, dtype pins. Those are read-time
// decisions and they stay in Python, because a corrected header row should be a re-read
// of what was uploaded rather than a request for the owner to send the workbook again.

export type DumpSlot = {
  /** Accepted filenames, canonical first; the rest are older names still readable. */
  files: string[];
  /** The sheet to take, or null for the workbook's first. */
  sheet: string | null;
  /** True when the sheet is named for its month and read off the workbook. */
  monthSheet: boolean;
  /** A dump that may simply not have been sent that day. */
  optional: boolean;
};

export const SLOTS: Record<string, DumpSlot> = {
  "bucketting": {
    files: ["rm_tracker_model.xlsx", "july0626_rm_tracker_v1.xlsx"],
    sheet: "Bucketting",
    monthSheet: false,
    optional: false,
  },
  "contract:CEW": {
    files: ["contract.xlsx"],
    sheet: "Tata_CEW - Q1 FY27",
    monthSheet: false,
    optional: true,
  },
  "contract:ERW": {
    files: ["contract.xlsx"],
    sheet: "Tata _ERW-Q4 FY26",
    monthSheet: false,
    optional: true,
  },
  "oem_key": {
    files: ["rm_tracker_model.xlsx", "july0626_rm_tracker_v1.xlsx"],
    sheet: "OEM_key_1_rev codes",
    monthSheet: false,
    optional: false,
  },
  "orders:hk_so": {
    files: ["orders.xlsx"],
    sheet: "hk_so",
    monthSheet: false,
    optional: true,
  },
  "orders:hk_str": {
    files: ["orders.xlsx"],
    sheet: "hk_str",
    monthSheet: false,
    optional: true,
  },
  "orders:jsr": {
    files: ["orders.xlsx"],
    sheet: "jsr",
    monthSheet: false,
    optional: true,
  },
  "receivables": {
    files: ["yf65.xlsx"],
    sheet: "Sheet1",
    monthSheet: false,
    optional: true,
  },
  "rfd": {
    files: ["rfd_4731.xlsx", "rfd.xlsx"],
    sheet: "Sheet5",
    monthSheet: false,
    optional: false,
  },
  "sales": {
    files: ["sales.xlsx"],
    sheet: "Sheet1",
    monthSheet: false,
    optional: false,
  },
  "sales_history": {
    files: ["sales_history.xlsx"],
    sheet: null,
    monthSheet: false,
    optional: true,
  },
  "sales_jul": {
    files: ["sales_jul.xlsx"],
    sheet: "Sheet1",
    monthSheet: false,
    optional: true,
  },
  "sales_q1": {
    files: ["sales_q1.xlsx"],
    sheet: "Sheet1",
    monthSheet: false,
    optional: true,
  },
  "sales_q4": {
    files: ["sales_q4.xlsx"],
    sheet: "Sheet1",
    monthSheet: false,
    optional: true,
  },
  "schedule": {
    files: ["rm_tracker_model.xlsx", "july0626_rm_tracker_v1.xlsx"],
    sheet: null,
    monthSheet: true,
    optional: false,
  },
  "schedule_supplement": {
    files: ["schedule_supplement.xlsx"],
    sheet: null,
    monthSheet: false,
    optional: true,
  },
  "signoff:hosur": {
    files: ["signoff.xlsx"],
    sheet: "hosur",
    monthSheet: false,
    optional: true,
  },
  "signoff:jsr": {
    files: ["signoff.xlsx"],
    sheet: "jsr",
    monthSheet: false,
    optional: true,
  },
  "signoff:khopoli": {
    files: ["signoff.xlsx"],
    sheet: "khopoli",
    monthSheet: false,
    optional: true,
  },
  "stock": {
    files: ["stock.xlsx"],
    sheet: "PLANT STOCKS",
    monthSheet: false,
    optional: false,
  },
  "transfers": {
    files: ["transfer.xlsx"],
    sheet: null,
    monthSheet: false,
    optional: true,
  },
  "vsm_stock": {
    files: ["rm_tracker_tvsm.xlsx"],
    sheet: "vsm stock",
    monthSheet: false,
    optional: false,
  },
  "vsm_tvsm": {
    files: ["rm_tracker_tvsm.xlsx"],
    sheet: "TVSM",
    monthSheet: false,
    optional: false,
  },
  "wip": {
    files: ["wip.xlsx"],
    sheet: null,
    monthSheet: false,
    optional: false,
  },
  "zmat": {
    files: ["zmat.xlsx"],
    sheet: "Sheet1",
    monthSheet: false,
    optional: false,
  },
};

/** Which slots a given filename can fill. Several slots share one workbook. */
export function slotsForFilename(filename: string): string[] {
  const name = filename.toLowerCase();
  return Object.entries(SLOTS)
    .filter(([, slot]) => slot.files.some((f) => f.toLowerCase() === name))
    .map(([key]) => key);
}

export const SLOT_NAMES = Object.keys(SLOTS);
