"""Emit the browser's dump adapters from the pipeline's own slot registry.

The uploader has to know which sheet of which workbook fills which slot. So does the
pipeline. Written twice they drift, and a drifted spec does not raise — it puts the
wrong sheet in the wrong slot and the page is quietly wrong. So the TypeScript is
generated from `scripts/sources.py` and checked in, and a test fails if the checked-in
copy no longer matches what the registry would produce.

    python3 tools/generate_adapters.py           # write lib/dumps/adapters.ts
    python3 tools/generate_adapters.py --check   # fail if it is out of date
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCRIPTS = REPO / ".claude" / "skills" / "refresh-tvsm-dashboard" / "scripts"
TARGET = REPO / "lib" / "dumps" / "adapters.ts"
sys.path.insert(0, str(SCRIPTS))

import sources as sources_module  # noqa: E402


def load_pipeline():
    spec = importlib.util.spec_from_file_location(
        "refresh_dashboard", SCRIPTS / "refresh_dashboard.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render() -> str:
    pipeline = load_pipeline()
    slots = dict(sources_module.SLOTS)
    slots.update(sources_module.slots_for_families(
        pipeline.ORDER_BOOK_SHEETS, pipeline.PRICING_SHEETS, pipeline.SIGNOFF_SHEETS
    ))

    entries = []
    for name, spec in sorted(slots.items()):
        sheet = spec.sheet
        if sheet is sources_module.CALLER_NAMES_THE_SHEET:
            # The schedule's sheet is named for the month it covers, so the uploader
            # reads it off the workbook rather than being told.
            sheet_value = "null"
            month_sheet = "true"
        elif isinstance(sheet, str):
            sheet_value = json.dumps(sheet)
            month_sheet = "false"
        else:
            sheet_value = "null"      # the workbook's first sheet
            month_sheet = "false"

        entries.append(
            f"  {json.dumps(name)}: {{\n"
            f"    files: {json.dumps(list(spec.files))},\n"
            f"    sheet: {sheet_value},\n"
            f"    monthSheet: {month_sheet},\n"
            f"    optional: {'true' if spec.optional else 'false'},\n"
            f"  }},"
        )

    return f'''// GENERATED by tools/generate_adapters.py — do not edit.
//
// One definition of what the pipeline reads, shared by the uploader and the refresh.
// The Python registry at .claude/skills/refresh-tvsm-dashboard/scripts/sources.py is the
// source; this is a projection of it, checked in so the browser bundle needs no Python,
// and asserted equal by the test suite so it cannot go stale.
//
// Note what is NOT here: header rows, column windows, dtype pins. Those are read-time
// decisions and they stay in Python, because a corrected header row should be a re-read
// of what was uploaded rather than a request for the owner to send the workbook again.

export type DumpSlot = {{
  /** Accepted filenames, canonical first; the rest are older names still readable. */
  files: string[];
  /** The sheet to take, or null for the workbook's first. */
  sheet: string | null;
  /** True when the sheet is named for its month and read off the workbook. */
  monthSheet: boolean;
  /** A dump that may simply not have been sent that day. */
  optional: boolean;
}};

export const SLOTS: Record<string, DumpSlot> = {{
{chr(10).join(entries)}
}};

/** Which slots a given filename can fill. Several slots share one workbook. */
export function slotsForFilename(filename: string): string[] {{
  const name = filename.toLowerCase();
  return Object.entries(SLOTS)
    .filter(([, slot]) => slot.files.some((f) => f.toLowerCase() === name))
    .map(([key]) => key);
}}

export const SLOT_NAMES = Object.keys(SLOTS);
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET.relative_to(REPO)} is out of date — "
                  f"run python3 tools/generate_adapters.py")
            return 1
        print("adapters are up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered)
    print(f"wrote {TARGET.relative_to(REPO)} ({rendered.count('files:')} slots)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
